### ISSUE TITLE
php71w-xml uses libxml2 2.7.6 from 2009

### ISSUE THREAD

**Issue by akeeman** [webtatic-rpms/php71w#1]
Hi Andy,

I'm not sure if this is the right location to bring this to you, but I'll give it a try.
I noticed that the php71w-xml uses libxml2 version 2.7.6, which is a bit outdated (it's from 2009).
Any possibility that this one gets [upgraded](http://xmlsoft.org/news.html)? For example, the very usefull LIBXML_HTML_NOIMPLIED is supported starting from 2.7.7.

**Comment by andytson** [comment]
Hi @akeeman, Webtatic fulfills its dependencies from the Linux distribution. In this case you are using CentOS 6, which supplies libxml2 version 2.7.6. CentOS 7 however has libxml2 version 2.9.1. If you would like to use such a later version of libxml2 I would recommend you switch over to CentOS 7, which will have updates for many other dependencies.
