### ISSUE TITLE
No package php71w-7.1.5 available.

### ISSUE THREAD

**Issue by o5** [webtatic-rpms/php71w#3]
Hello, I just try to install latest version of PHP, but I'm getting error: 

> No package php71w-7.1.5 available.

Dockerfile
```
FROM centos:7
...
RUN yum install -y epel-release && \$
    yum localinstall -y https://mirror.webtatic.com/yum/el7/webtatic-release.rpm && \$
    yum update -y && \$
    yum install -y \$
        php71w-7.1.5 \$
...
```

I also tried `php71w-7.1.5-1` but it ends with same error.

**Comment by andytson** [comment]
Sorry, the RPM's weren't moved over to the stable repository, but are now
