### ISSUE TITLE
latest updates on RHEL 7.3 openssl 1.0.2 dependency

### ISSUE THREAD

**Issue by tbenr** [webtatic-rpms/php71w#5]
Hi,
latest updates require openssl 1.0.2, which is not available on redhat 7.3.

is it intended to be like that? Am I missing somethig to solve the yum update issue?

Thanks

![image](https://user-images.githubusercontent.com/15999009/31374983-664f71a6-ada0-11e7-929d-86df61fadc8d.png)

**Comment by tbenr** [comment]
version 7.1.6, which i successfully installed (no openssl1.0.2 dependency, I guess) disappeared from the repo source, so I cannot stick to this version (I need to install php71w-soap)

**Comment by andytson** [comment]
Webtatic supports only the latest minor release of RHEL/CentOS. It is bad practice to pin the OS to a minor release as you stop getting security updates from them when a new minor release is made (except when paying more for the RHEL Extended Upgrade Subscription(EUS), however that doesn't fund Webtatic)

Its unlikely you are using EUS, so if that is the case, unpinning from RHEL 7.3 so 7.4 is installed is best.
